# Dependencies
markdown:         redcarpet
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Regin
tagline:          'gudarnas återkomst'
description:      'Regin - Lajvet för kreativa spelare som vill forma sin karaktärs och världens utveckling.'
url:              http://regin.mumma.nu
baseurl:          ''

paginate:         5
paginate_path:    "blog/page:num"
banner:           banner.jpg

author:
  name:           'Patrik'
  url:            https://www.mumma.nu

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/paven/regin

gems:
- jekyll-mentions
- jekyll-sitemap

first_page:
  url: /index/
